[build]
  command = "jekyll build && cp _redirects _site/"
  publish = "_site"


# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "jekyll build -D && cp _redirects _site/"
